/* Catmurai motion: authored pose clips + time-based combat choreography. */
const motionImage=new Image();let motionTexture=null,motionError='',motionFrames=[];
motionImage.onload=()=>{try{const surface=document.createElement('canvas');surface.width=motionImage.naturalWidth;surface.height=motionImage.naturalHeight;const c=surface.getContext('2d',{willReadFrequently:true});c.drawImage(motionImage,0,0);const pixels=c.getImageData(0,0,surface.width,surface.height),d=pixels.data;for(let i=0;i<d.length;i+=4){const excess=d[i+1]-Math.max(d[i],d[i+2]);if(excess>25&&d[i+1]>85){const alpha=1-Math.min(1,(excess-25)/65);d[i+3]=Math.round(255*alpha);d[i+1]=Math.min(d[i+1],Math.max(d[i],d[i+2])+15)}}c.putImageData(pixels,0,0);motionTexture=surface;motionFrames=prepareFrames(surface);document.body.dataset.motion='ready'}catch(e){motionError=e.message;log('Animation texture could not load. Reload using the local server.')}};
motionImage.onerror=()=>{motionError='Animation atlas not found';log(motionError)};motionImage.src='assets/catmurai-motion.png';
const CLIPS={idle:{row:0,frames:[0],duration:2,loop:true},walk:{row:0,frames:[0,1,5,6,4,2,3,7],duration:.8,loop:true},attack:{row:1,frames:[0,1,2,3,4,5],duration:.72,impact:.36},moon:{row:1,frames:[0,1,2,2,3,4,5],duration:.86,impact:.50},whirl:{row:3,frames:[0,1,2,3,4,5,1,2,3,4,5],duration:.95,impact:.32},mend:{row:2,frames:[0,1,2,3,3,5],duration:1.15,impact:.57},guard:{row:2,frames:[0,1,2,3,2,5],duration:1.05,impact:.5},hurt:{row:1,frames:[0,0,5],duration:.3},death:{row:1,frames:[0,5],duration:1.25},potion:{row:2,frames:[0,1,2,5],duration:.7,impact:.35}};
const motion={state:'idle',elapsed:0,walkPhase:0,facing:1,travel:0,events:[],fx:[],ghosts:[],preview:null,paused:false,speed:1,lastX:p.x,lastY:p.y};
function clipFrame(name,elapsed){const c=CLIPS[name];const progress=c.loop?(elapsed%c.duration)/c.duration:Math.min(.999999,elapsed/c.duration);return{row:c.row,col:c.frames[Math.floor(Math.max(0,progress)*c.frames.length)],progress}}
function startMotion(name){motion.state=name;motion.elapsed=0;if(target&&Math.abs(target.x-p.x)>4)motion.facing=target.x>p.x?1:-1;motion.fx.push({name,x:p.x,y:p.y,elapsed:0,duration:CLIPS[name].duration+.35,face:motion.facing})}
function busy(){return !CLIPS[motion.state].loop&&motion.elapsed<CLIPS[motion.state].duration}
const instantHit=hit;
hit=function(e,damage){if(e.dead)return;if(!busy())startMotion('attack');motion.events.push({remaining:Math.max(.01,(CLIPS[motion.state].impact||.36)-motion.elapsed),e,damage:damage*(typeof talentBonus==='function'&&['moon','whirl'].includes(motion.state)?1+talentBonus('skill'):1),origin:{x:p.x,y:p.y},range:motion.state==='whirl'?220:180})};
skill=function(n){if(!running||$('#modal').open||motion.preview||busy()||cooldown[n]>0)return;const costs=[12,24,28,18];if(p.mp<costs[n])return log('Not enough spirit.');if(n<2&&(!target||target.dead||Math.hypot(target.x-p.x,target.y-p.y)>150))return log('Select an enemy within blade range.');p.mp-=costs[n];cooldown[n]=[4,8,12,15][n]*(typeof talentBonus==='function'?1-talentBonus('cooldown'):1);const name=['moon','whirl','mend','guard'][n];startMotion(name);attackCD=CLIPS[name].duration+.2;destination=null;if(n===0)hit(target,38+p.level*8+p.weapon*12);if(n===1)for(const e of enemies)if(!e.dead&&Math.hypot(e.x-p.x,e.y-p.y)<190)hit(e,30+p.level*7);if(n===2)motion.events.push({remaining:.57,action:'heal',amount:65});if(n===3)motion.events.push({remaining:.5,action:'guard'})};
potion=function(){if(!running||$('#modal').open||motion.preview||busy()||p.hp>=maxhp()||p.potions<1)return;p.potions--;startMotion('potion');motion.events.push({remaining:.35,action:'heal',amount:90});save()};$('#potion').onclick=()=>potion();
const simulationUpdate=update;
update=function(dt){if(!running||$('#modal').open||document.hidden)return;let step=dt*(motion.preview?motion.speed:1);if(motion.preview){if(!motion.paused){motion.elapsed+=step;if(motion.elapsed>=CLIPS[motion.state].duration+.4){startMotion(motion.preview)}motion.fx.forEach(f=>f.elapsed+=step);motion.fx=motion.fx.filter(f=>f.elapsed<f.duration);time+=step}return}
const hpBefore=p.hp,oldX=p.x,oldY=p.y;let savedKeys=keys,savedDestination=destination,savedTarget=target;const locked=busy();if(locked){keys={};destination=null;target=null;attackCD=Math.max(attackCD,.05)}simulationUpdate(dt);if(locked){keys=savedKeys;destination=savedDestination;target=savedTarget?.dead?null:savedTarget;p.moving=false}let distance=Math.hypot(p.x-oldX,p.y-oldY);if(distance>500){motion.ghosts.push({x:oldX,y:oldY,elapsed:0,duration:1.25,face:motion.facing,death:true});motion.events=[];target=null;destination=null;keys={};startMotion('idle')}else if(p.hp<hpBefore&&!busy())startMotion('hurt');motion.travel+=distance;motion.walkPhase+=distance/120*.8;if(distance>.1&&Math.abs(p.x-oldX)>.1)motion.facing=p.x>oldX?1:-1;
motion.elapsed+=dt;if(!busy()){let next=distance>.1?'walk':'idle';if(motion.state!==next){motion.state=next;motion.elapsed=0}}if(motion.state==='walk')motion.elapsed=motion.walkPhase;
for(const event of motion.events){event.remaining-=dt;if(event.remaining<=0){if(event.e&&!event.e.dead&&Math.hypot(event.e.x-p.x,event.e.y-p.y)<=event.range){const foe=event.e;instantHit(foe,event.damage,event.hitScale||1);foe.flash=.2;if(foe.dead)motion.ghosts.push({x:foe.x,y:foe.y,elapsed:0,duration:.65,enemy:{...foe,dead:0,hp:0}})}else if(event.action==='heal'){let actual=Math.min(event.amount*(typeof talentBonus==='function'?1+talentBonus('healing'):1),maxhp()-p.hp);p.hp+=actual;float('+'+Math.round(actual),p.x,p.y-80,'#91edc3')}else if(event.action==='guard'){buff=7;log('Iron fur · guard active for 7 seconds')}}}motion.events=motion.events.filter(e=>e.remaining>0);for(const f of motion.fx)f.elapsed+=dt;motion.fx=motion.fx.filter(f=>f.elapsed<f.duration);for(const g of motion.ghosts)g.elapsed+=dt;motion.ghosts=motion.ghosts.filter(g=>g.elapsed<g.duration);for(const e of enemies)e.flash=Math.max(0,(e.flash||0)-dt);
};
function drawPose(state,elapsed,x,y,face=1,opacity=1){if((state==='walk'||state==='idle')&&walkFrames.length===8){const frame=state==='walk'?clipFrame(state,elapsed).col:0;ctx.save();ctx.globalAlpha*=opacity;ctx.translate(x,y);ctx.scale(face,1);const scale=.51;const anchor=[236,235,236,236,242,243,241,242][frame];if(state==='idle')ctx.scale(1,1+Math.sin(elapsed*1.8)*.003);ctx.drawImage(walkFrames[frame],-anchor*scale,-397*scale,walkFrames[frame].width*scale,walkFrames[frame].height*scale);if(typeof drawWeaponEnchant==='function')drawWeaponEnchant('walk',frame,anchor,397,scale);ctx.restore();return}if(state==='walk'&&walkFrames.length!==8)elapsed=0;if(!motionTexture){if(heroArt.complete&&heroArt.naturalWidth)ctx.drawImage(heroArt,x-68,y-196,136,204);return}let frame=clipFrame(state,elapsed);const rows=[{y:0,h:263,foot:259},{y:269,h:242,foot:238},{y:514,h:246,foot:242},{y:763,h:253,foot:242}],r=rows[frame.row],scale=.8;ctx.save();ctx.globalAlpha*=opacity;ctx.translate(x,y);ctx.scale(face,1);if(state==='idle')ctx.scale(1,1+Math.sin(elapsed*3)*.006);if(state==='hurt')ctx.translate(-Math.sin(frame.progress*Math.PI)*12,0);if(state==='death'){ctx.rotate(-Math.min(1,frame.progress*1.8)*1.45);ctx.scale(1,1-frame.progress*.12)}const anchors=[[150,150,150,150,150,150],[125,135,128,124,134,136],[131,126,130,122,125,137],[126,129,127,125,121,135]];const tile=motionFrames[frame.row*6+frame.col];if(tile)ctx.drawImage(tile,-anchors[frame.row][frame.col]*scale,-r.foot*scale,tile.width*scale,r.h*scale);else ctx.drawImage(motionTexture,frame.col*256,r.y,256,r.h,-anchors[frame.row][frame.col]*scale,-r.foot*scale,256*scale,r.h*scale);if(typeof drawWeaponEnchant==='function')drawWeaponEnchant(frame.row,frame.col,anchors[frame.row][frame.col],r.foot,scale);ctx.restore()}
const sceneActor=actor;
actor=function(a,kind){if(kind!==0){ctx.save();if(a.flash){ctx.filter='brightness(1.8)'}let s=pos(a.x,a.y);if(a.cd>1.22){ctx.translate(s.x,s.y);ctx.rotate(Math.sin((1.5-a.cd)*12)*.08);ctx.translate(-s.x,-s.y)}sceneActor(a,kind);ctx.restore();return}let s=pos(a.x,a.y);ellipse(s.x,s.y+2,37,11,'#040b1680');drawPose(motion.state,motion.elapsed,s.x,s.y,motion.facing);text('C A T M U R A I',s.x,s.y-221,'#f4dfb5',11);if(buff){glow(s.x,s.y-70,95,'#e6be6a24');ctx.save();ctx.strokeStyle='#e5c78390';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(s.x,s.y-86,70+Math.sin(time*3)*2,108,0,0,Math.PI*2);ctx.stroke();ctx.restore()}};
function drawMotionEffects(){for(const f of motion.fx){let s=pos(f.x,f.y),u=f.elapsed/f.duration,fade=Math.sin(Math.min(1,u)*Math.PI);ctx.save();ctx.globalAlpha=fade;const cast=['mend','potion','guard'].includes(f.name);if(cast){let color=f.name==='guard'?'#efca79':'#82f1c4';glow(s.x,s.y-65,110,color+'30');ctx.strokeStyle=color;ctx.lineWidth=2;for(let j=0;j<3;j++){ctx.beginPath();ctx.ellipse(s.x,s.y-j*28-u*45,35+u*40,13+u*12,0,0,Math.PI*2);ctx.stroke()}for(let j=0;j<18;j++){let a=j*2.4+u*5,r=35+Math.sin(j)*20;circle(s.x+Math.sin(a)*r,s.y-20-u*150+(j%5)*12,1.5,color)}}if(f.name==='whirl'){for(let j=0;j<3;j++){ctx.strokeStyle=['#fff2d4','#e78497','#ffcc8f'][j];ctx.lineWidth=5-j;ctx.shadowColor='#ed8192';ctx.shadowBlur=12;ctx.beginPath();ctx.ellipse(s.x,s.y-50,90+j*17,34+j*9,-.15,u*18+j,u*18+j+4);ctx.stroke()}}if(['attack','moon'].includes(f.name)&&f.elapsed>=CLIPS[f.name].impact&&f.elapsed<CLIPS[f.name].impact+.26){ctx.translate(s.x,s.y-80);ctx.scale(f.face,1);ctx.strokeStyle=f.name==='moon'?'#c9f2ff':'#ffe3be';ctx.shadowColor=f.name==='moon'?'#68cfff':'#ee8c83';ctx.shadowBlur=18;ctx.lineWidth=f.name==='moon'?9:5;ctx.beginPath();ctx.ellipse(0,0,105,66,-.6,-1+u*3,1.5+u*3);ctx.stroke()}if(f.name==='walk'){for(let j=0;j<5;j++)circle(s.x+j*6-12,s.y-u*12,2,'#b6ad8c')}ctx.restore()}for(const g of motion.ghosts){let s=pos(g.x,g.y);ctx.save();ctx.globalAlpha=1-g.elapsed/g.duration;if(g.death)drawPose('death',g.elapsed,s.x,s.y,g.face);else{ctx.translate(s.x,s.y);ctx.rotate(g.elapsed*1.6);ctx.translate(-s.x,-s.y);typeof drawWorldCorpse==='function'?drawWorldCorpse(g.enemy):sceneActor(g.enemy,g.enemy.kind===2?3:g.enemy.kind===1?2:1)}ctx.restore()}}
const sceneDraw=draw;draw=function(){sceneDraw();if(running)drawMotionEffects();if(motion.preview){text('ANIMATION PREVIEW · '+motion.preview.toUpperCase()+' · FRAME '+(clipFrame(motion.state,motion.elapsed).col+1),W/2,H-165,'#f3d49c',12)}};
function enterPreview(name){if(!running)return;motion.preview=name;motion.events=[];motion.fx=[];target=null;destination=null;keys={};startMotion(name);$('#animationPanel').classList.remove('hidden')}
function exitPreview(){motion.preview=null;motion.fx=[];motion.paused=false;startMotion('idle');$('#animationPanel').classList.add('hidden')}
$('#animationOpen').onclick=()=>enterPreview('walk');$('#animationExit').onclick=exitPreview;document.querySelectorAll('[data-animation]').forEach(b=>b.onclick=()=>enterPreview(b.dataset.animation));$('#animationPause').onclick=()=>{motion.paused=!motion.paused;$('#animationPause').textContent=motion.paused?'Resume':'Pause'};$('#animationSpeed').onchange=e=>motion.speed=Number(e.target.value);$('#animationFlip').onclick=()=>motion.facing*=-1;
addEventListener('keydown',e=>{if(e.key==='Escape'&&motion.preview)exitPreview()});
$('#animationStep').onclick=()=>{motion.paused=true;$('#animationPause').textContent='Resume';const c=CLIPS[motion.state];motion.elapsed=(motion.elapsed+c.duration/c.frames.length)%c.duration;motion.fx.forEach(f=>f.elapsed=motion.elapsed)};

function isolateFrame(surface,sx,sy,w,h,largestOnly=false){const tile=document.createElement('canvas');tile.width=w;tile.height=h;const c=tile.getContext('2d',{willReadFrequently:true});c.drawImage(surface,sx,sy,w,h,0,0,w,h);let im=c.getImageData(0,0,w,h),data=im.data,n=w*h,labels=new Int32Array(n),queue=new Int32Array(n),components=[null],largest=0;for(let i=0;i<n;i++){if(labels[i]||data[i*4+3]<30)continue;const id=components.length;let head=0,tail=1,edge=false;queue[0]=i;labels[i]=id;while(head<tail){const v=queue[head++],x=v%w,y=Math.floor(v/w);if(x<2||x>w-3||y<1||y>=h-1)edge=true;const neighbors=[x>0?v-1:-1,x<w-1?v+1:-1,y>0?v-w:-1,y<h-1?v+w:-1];for(const k of neighbors)if(k>=0&&!labels[k]&&data[k*4+3]>=30){labels[k]=id;queue[tail++]=k}}components.push({size:tail,edge});if(!largest||tail>components[largest].size)largest=id}for(let i=0;i<n;i++){let id=labels[i];if(!id||(id!==largest&&(largestOnly||components[id].edge||components[id].size<40)))data[i*4+3]=0}c.putImageData(im,0,0);return tile}
function prepareFrames(surface){const bands=[[0,263],[269,242],[514,246],[763,253]],frames=[];for(let row=0;row<4;row++)for(let col=0;col<6;col++)frames.push(isolateFrame(surface,col*256,bands[row][0],row===1&&col===4?318:256,bands[row][1]));return frames}

const walkImage=new Image();let walkFrames=[];
walkImage.onload=()=>{try{const surface=document.createElement('canvas');surface.width=walkImage.naturalWidth;surface.height=walkImage.naturalHeight;const c=surface.getContext('2d',{willReadFrequently:true});c.drawImage(walkImage,0,0);let im=c.getImageData(0,0,surface.width,surface.height),d=im.data;for(let i=0;i<d.length;i+=4){const excess=d[i+1]-Math.max(d[i],d[i+2]);if(excess>25&&d[i+1]>85){d[i+3]=Math.round(255*(1-Math.min(1,(excess-25)/65)));d[i+1]=Math.min(d[i+1],Math.max(d[i],d[i+2])+15)}}c.putImageData(im,0,0);let cw=surface.width/4,ch=surface.height/2;for(let i=0;i<8;i++)walkFrames.push(isolateFrame(surface,Math.floor(i%4*cw)+3,Math.floor(i/4)*Math.floor(ch)+3,Math.floor(cw)-6,Math.floor(ch)-6));document.body.dataset.walk='ready'}catch(e){log('Walk texture load failed: '+e.message)}};walkImage.src='assets/catmurai-walk.png';


