/* Shrine trials: explicit challenge entry, telegraphed mechanics, persistent rewards. */
const BOSS_TRIALS=[
 {id:'fang',name:'Hollow Fang · Awakened',level:4,x:1150,y:-750,color:'#fa9779',pattern:'slam',weapon:'fangrelic',desc:'Dodge the crimson ground slam. Below 50% health, twin slams strike faster.'},
 {id:'moon',name:'Lady of the Broken Moon',level:7,x:-1150,y:-850,color:'#c399ff',pattern:'ring',weapon:'moonrelic',desc:'Alternate between dodging targeted starbursts and moving inside or outside the Moonfall ring.'},
 {id:'storm',name:'Raijin · Stormforged',level:10,x:1100,y:1050,color:'#84e9ed',pattern:'line',weapon:'stormrelic',desc:'Sidestep the marked lightning lane. Enrage calls a second crossing lane.'}
];
p.bossRewards=p.bossRewards&&typeof p.bossRewards==='object'?p.bossRewards:{};p.bossTokens=Number.isInteger(p.bossTokens)&&p.bossTokens>=0?p.bossTokens:0;
let trial=null,trialWarnings=[];
function beginTrial(id){const def=BOSS_TRIALS.find(b=>b.id===id);if(!def||trial||p.level<def.level||Math.hypot(p.x,p.y)>240||busy())return false;stopAutoFarm();target=null;destination=null;keys={};motion.events=[];enemyStrikes.length=0;const hp=Math.max(1800,(15+p.level*5+p.weapon*8+equippedWeapon().damage)*28);const foe={id:200+BOSS_TRIALS.indexOf(def),encounter:id,kind:2,name:def.name,x:def.x,y:def.y,homeX:def.x,homeY:def.y,hp,max:hp,dead:0,cd:0};enemies.push(foe);trial={def,foe,clock:1.5,phase:1,attacks:0};trialWarnings=[];p.x=def.x-170;p.y=def.y+100;p.hp=maxhp();p.mp=80;cam.x=p.x;cam.y=p.y;target=foe;$('#modal').close();log(def.name+' · '+def.desc);return true}
function endTrial(won=false){if(!trial)return;const foe=trial.foe;enemies.splice(enemies.indexOf(foe),1);trial=null;trialWarnings=[];target=null;destination=null;motion.events=[];if(!won)log('Trial ended. Return to the shrine to challenge again.')}
function claimBossReward(e){if(!trial||trial.foe!==e)return;const def=trial.def,first=!p.bossRewards[def.id];p.bossRewards[def.id]=true;p.bossTokens+=first?3:1;p.gold+=first?500:100;p.xp+=first?300:100;if(first)p.armory[def.weapon]=Math.max(4,p.armory[def.weapon]||0);while(p.xp>=p.level*100){p.xp-=p.level*100;p.level++}p.hp=maxhp();p.mp=80;endTrial(true);p.x=0;p.y=160;save();modal(`<small>TRIAL VICTORY</small><h2>${def.name} defeated</h2><p>${first?'First-clear reward: '+WEAPONS.find(w=>w.id===def.weapon).name+' +4 added to your armory.':'Repeat-clear reward earned.'}</p><p>+${first?500:100} gold · +${first?300:100} XP · +${first?3:1} boss seals</p><p>Equip your relic through I. Spend 3 seals on a guaranteed enchantment in the Boss Trials panel.</p>`)}
function warningContains(w,x,y){const d=Math.hypot(x-w.x,y-w.y);if(w.kind==='ring')return d>=75&&d<=245;if(w.kind==='line'){const dx=x-w.x,dy=y-w.y;return Math.abs(dx*Math.cos(w.angle)+dy*Math.sin(w.angle))<=280&&Math.abs(-dx*Math.sin(w.angle)+dy*Math.cos(w.angle))<=48}return d<=105}
function makeTrialAttack(){const t=trial,e=t.foe,kind=t.def.pattern==='ring'&&t.attacks%2===1?'slam':t.def.pattern,delay=t.phase===2?.95:1.35;t.attacks++;const base={kind,x:kind==='ring'?e.x:p.x,y:kind==='ring'?e.y:p.y,angle:Math.atan2(p.y-e.y,p.x-e.x),remaining:delay,duration:delay};trialWarnings.push(base);if(t.phase===2&&kind!=='ring')trialWarnings.push({...base,x:kind==='slam'?p.x+95:base.x,angle:base.angle+Math.PI/2,remaining:delay+.45,duration:delay+.45});npcFrame(e).attack=.65}
function updateTrial(dt){if(!trial)return;const t=trial,e=t.foe;if(Math.hypot(p.x,p.y)<240||Math.hypot(p.x-t.def.x,p.y-t.def.y)>650){endTrial();return}t.phase=e.hp/e.max<=.5?2:1;t.clock-=dt;if(t.clock<=0){makeTrialAttack();t.clock=t.phase===2?2.4:3.3}for(const w of trialWarnings){w.remaining-=dt;if(w.remaining<=0&&warningContains(w,p.x,p.y)){let damage=Math.round(maxhp()*(t.phase===2?.24:.18)*(buff?.35:1)*(1-talentBonus('armor')));p.hp-=damage;float('-'+damage,p.x,p.y-75,t.def.color)}}trialWarnings=trialWarnings.filter(w=>w.remaining>0);if(p.hp<=0){p.hp=maxhp();p.mp=80;p.x=0;p.y=160;motion.events=[];startMotion('idle');endTrial();save();log('The shrine restores you. The trial can be retried.')}}
function spendBossSeals(){if(p.bossTokens<3||busy())return false;p.bossTokens-=3;p.weapon++;p.armory[p.equippedWeapon]=p.weapon;save();return true}
function openTrials(){if(!running||busy())return;modal(`<small>CRIMSON SHRINE · BOSS TRIALS</small><h2>Legends of Moonfall</h2><p>${p.bossTokens} boss seals · First clear: exclusive +4 relic, 500 gold, 300 XP, 3 seals. Repeat: 100 gold, 100 XP, 1 seal.</p>${BOSS_TRIALS.map(b=>`<article class="trial-card"><h3 style="color:${b.color}">${b.name} ${p.bossRewards[b.id]?'✓':''}</h3><p>${b.desc}</p><p>Level ${b.level} · Relic: ${WEAPONS.find(w=>w.id===b.weapon).name}</p><button data-trial="${b.id}" ${trial||p.level<b.level||Math.hypot(p.x,p.y)>240?'disabled':''}>Enter trial</button></article>`).join('')}<p>Enter from the shrine. Each trial restores health and spirit. Dodge with WASD; leave the arena to retreat. Auto-farm is disabled.</p><button id="sealEnchant" ${p.bossTokens<3||trial?'disabled':''}>Enchant equipped weapon +1 · 3 seals</button>`);document.querySelectorAll('[data-trial]').forEach(b=>b.onclick=()=>beginTrial(b.dataset.trial));$('#sealEnchant').onclick=()=>{spendBossSeals();openTrials()}}
const trialButton=document.createElement('button');trialButton.textContent='Boss trials [B]';trialButton.onclick=openTrials;$('#talk').after(trialButton);addEventListener('keydown',e=>{if(e.key.toLowerCase()==='b'&&running&&!$('#modal').open&&!motion.preview)openTrials()});
const trialUpdate=update;update=function(dt){const active=running&&!$('#modal').open&&!document.hidden&&!motion.preview;trialUpdate(dt);if(active)updateTrial(dt)};
const trialDraw=draw;draw=function(){$('#hud').classList.toggle('in-trial',!!trial);trialDraw();if(!running||!trial)return;for(const w of trialWarnings){const s=pos(w.x,w.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.62);ctx.strokeStyle=trial.def.color;ctx.fillStyle=trial.def.color+'35';ctx.lineWidth=3;ctx.beginPath();if(w.kind==='line'){ctx.rotate(w.angle);ctx.rect(-280,-48,560,96)}else{ctx.arc(0,0,w.kind==='ring'?245:105,0,Math.PI*2);if(w.kind==='ring')ctx.arc(0,0,75,0,Math.PI*2,true)}ctx.fill('evenodd');ctx.stroke();ctx.restore();text(Math.max(0,w.remaining).toFixed(1)+'s',s.x,s.y-10,'#fff1d5',16)}const e=trial.foe;ctx.fillStyle='#091521e8';ctx.fillRect(W/2-240,18,480,58);ctx.fillStyle='#372537';ctx.fillRect(W/2-220,57,440,9);ctx.fillStyle=trial.def.color;ctx.fillRect(W/2-220,57,440*Math.max(0,e.hp/e.max),9);text(e.name+' · '+(trial.phase===2?'ENRAGED':'PHASE I'),W/2,43,trial.def.color,16)};
const bossFarmToggle=toggleAutoFarm;toggleAutoFarm=function(){if(trial)return log('Auto-farm is unavailable during boss trials.');bossFarmToggle()};$('#autoFarm').onclick=()=>toggleAutoFarm();
const bossActor=actor;actor=function(a,kind){if(!a.encounter)return bossActor(a,kind);const s=pos(a.x,a.y),row=a.encounter==='moon'?1:a.encounter==='storm'?2:3;ellipse(s.x,s.y,54,18,'#080d1c99');ctx.save();if(a.flash)ctx.filter='brightness(1.7)';npcSprite(row,trialWarnings.length?3+Math.floor(time*5)%3:Math.floor(time*2)%2,s.x,s.y,220,p.x>=a.x?1:-1);ctx.restore();text(a.name,s.x,s.y-235,BOSS_TRIALS.find(b=>b.id===a.encounter).color,12)};
