sanitizeTalents();p.hp=maxhp();
function openTalents(){if(!running)return;keys={};$('#modal').classList.add('talent-window');modal('<div id="talentContent"></div>');renderTalents()}
function renderTalents(){const available=talentPoints();$('#talentContent').innerHTML=`<div class="talent-heading"><div><small>CHARACTER PROGRESSION</small><h2>Paths of the Crimson Moon</h2><p>One point each level after level 1. Master a talent to unlock the next.</p></div><div class="point-counter"><b>${available}</b><span>POINTS AVAILABLE</span></div></div><div class="talent-branches">${['Blade','Guardian','Spirit'].map((branch,i)=>`<section class="talent-branch branch-${i}"><h3>${['⚔','♜','◈'][i]} ${branch}</h3><p>${['Precision & finishing power','Vitality & resilience','Recovery & mastery'][i]}</p>${TALENTS.filter(t=>t.branch===branch).map(t=>{const rank=p.talents[t.id]||0,locked=t.parent&&(p.talents[t.parent]||0)<3,can=available>0&&rank<t.max&&!locked;return `<div class="talent-node ${rank?'invested':''} ${locked?'locked':''}"><div class="node-top"><span class="talent-icon">${t.icon}</span><div><strong>${t.name}</strong><span class="rank">${rank} / ${t.max} ranks</span></div></div><p>${t.description}</p><div class="rank-dots">${[1,2,3].map(n=>`<i class="${rank>=n?'filled':''}"></i>`).join('')}</div><button data-talent="${t.id}" ${can?'':'disabled'}>${locked?'Requires '+TALENTS.find(n=>n.id===t.parent).name+' 3/3':rank===t.max?'Mastered':available?'Learn · 1 point':'No points available'}</button></div>`}).join('')}</section>`).join('')}</div><div class="talent-bottom"><span>LEVEL ${p.level} · ${talentSpent()} POINTS SPENT · Bonuses apply immediately</span><button id="respec">Reset talents · Free</button></div>`;document.querySelectorAll('[data-talent]').forEach(b=>b.onclick=()=>{if(learnTalent(b.dataset.talent))renderTalents()});$('#respec').onclick=()=>{resetTalents();renderTalents()}}
$('#talentsButton').onclick=openTalents;$('#modal').addEventListener('close',()=>{$('#modal').classList.remove('talent-window');keys={}});addEventListener('keydown',e=>{if(e.key.toLowerCase()==='n'&&!e.repeat&&!$('#modal').open)openTalents()});
const modernInventory=inventory;inventory=function(){modernInventory();$('#modalBody').insertAdjacentHTML('beforeend',`<div class="character-summary"><span>Maximum health <b>${maxhp()}</b></span><span>Damage bonus <b>+${Math.round(talentBonus('damage')*100)}%</b></span><span>Armor reduction <b>${Math.round(talentBonus('armor')*100)}%</b></span><span>Talent points <b>${talentPoints()}</b></span></div>`)};$('#inventory').onclick=()=>inventory();
const help=['Moon Cut · 12 spirit · 4s base cooldown. A powerful single-target strike.','Whirlwind · 24 spirit · 8s base cooldown. Hit enemies around you.','Spirit Mend · 28 spirit · 12s base cooldown. Restore health.','Iron Fur · 18 spirit · 15s base cooldown. Reduce damage for 7 seconds.'];document.querySelectorAll('[data-skill]').forEach((b,i)=>{b.title=help[i];b.querySelector('span').textContent=['Moon cut','Whirlwind','Spirit mend','Iron fur'][i];b.insertAdjacentHTML('afterbegin',`<kbd>${i+1}</kbd>`)});$('#potion').title='Healing potion · Q · Restores 90 health before talents';$('#potion').insertAdjacentHTML('afterbegin','<kbd>Q</kbd>');$('#close').setAttribute('aria-label','Close panel');
const mini=$('#minimap').getContext('2d');let hudTick=0;
const modernUpdate=update;update=function(dt){modernUpdate(dt);if(!running)return;hudTick+=dt;if(hudTick<.1)return;hudTick=0;$('#mpText').textContent=Math.floor(p.mp)+' / 80 SP';$('#talentsButton').textContent='Talents [N]'+(talentPoints()?' · '+talentPoints():'');$('#talentsButton').classList.toggle('has-points',talentPoints()>0);$('#castStatus').textContent=busy()?({attack:'Katana strike',moon:'Moon Cut',whirl:'Whirlwind',mend:'Spirit Mend',guard:'Iron Fur',potion:'Healing potion',hurt:'Staggered'}[motion.state]||''):'Click to move  ·  TAB target  ·  1–4 skills';if(target){$('#target').style.setProperty('--target-health',Math.max(0,target.hp/target.max)*100+'%')}mini.fillStyle='#10262c';mini.fillRect(0,0,160,135);mini.strokeStyle='#728475';mini.lineWidth=5;mini.beginPath();mini.moveTo(4,105);mini.lineTo(156,25);mini.stroke();function point(x,y,color,r){mini.fillStyle=color;mini.beginPath();mini.arc(80+x/24,68+y/24,r,0,7);mini.fill()}point(0,0,'#e2cc8c',4);for(const e of enemies)if(!e.dead)point(e.x,e.y,e.kind===2?'#d59ce4':'#d37d76',e.kind===2?3:1.6);point(p.x,p.y,'#a8f5ed',3.5);mini.fillStyle='#d3ceb9';mini.font='10px sans-serif';mini.fillText('N',77,12);$('#mapCoordinates').textContent=Math.round(p.x)+' , '+Math.round(p.y)+' · ◆ Shrine';};



const enchantInventory=inventory;inventory=function(){enchantInventory();const e=enchantStyle(p.weapon);$('#modalBody').insertAdjacentHTML('beforeend',`<p style="color:${e.color}">✦ Katana +${e.level} · ${e.name}</p><p class="muted">Enchantment glow: +1 frost · +4 azure · +7 violet · +10 arcane · +15 crimson. Temper your blade to strengthen its aura.</p>`)};$('#inventory').onclick=()=>inventory();
