/* Shadow Ascension: temporary visual form; armory ownership and enchantment stay intact. */
const shadow={active:false,remaining:0,cooldown:0,elapsed:0,burst:0,ready:false};
function ascendShadow(){
 if(!running||$('#modal').open||motion.preview||busy()||shadow.active||shadow.cooldown>0||p.hp<=0)return false;
 if(!shadow.ready){log('Shadow form is still loading.');return false}
 if(p.mp<40){log('Shadow Ascension requires 40 spirit.');return false}
 p.mp-=40;shadow.active=true;shadow.remaining=15;shadow.cooldown=60;shadow.elapsed=0;shadow.burst=1;
 startMotion('guard');log('Shadow Ascension · 15 seconds · damage +25%');return true;
}
function endShadow(){shadow.active=false;shadow.remaining=0;shadow.burst=1;syncWeaponClips()}
function tickShadow(dt,defeated=false){shadow.cooldown=Math.max(0,shadow.cooldown-dt);shadow.burst=Math.max(0,shadow.burst-dt);if(!shadow.active)return;shadow.elapsed+=dt;shadow.remaining=Math.max(0,shadow.remaining-dt);if(defeated||(!shadow.remaining&&!busy()))endShadow()}
const mortalClass=weaponClass;weaponClass=function(){return shadow.active?'sword':mortalClass()};
const mortalDamage=weaponDamage;weaponDamage=function(d,skillHit=false){return Math.round(mortalDamage(d,skillHit)*(shadow.active&&shadow.remaining>0?1.25:1))};
const shadowBaseUpdate=update;update=function(dt){const active=running&&!$('#modal').open&&!document.hidden&&!motion.preview,x=p.x,y=p.y;shadowBaseUpdate(dt);if(active)tickShadow(dt,p.hp<=0||Math.hypot(p.x-x,p.y-y)>500);updateShadowButton();if(shadow.active&&shadow.elapsed<1.05)$('#castStatus').textContent='Shadow Ascension'};
const shadowFrames=[],shadowImage=new Image(),shadowAura=new Image();
shadowAura.src='assets/shadow-aura.png';
shadowImage.onload=()=>{try{
 const s=document.createElement('canvas');s.width=shadowImage.naturalWidth;s.height=shadowImage.naturalHeight;if(s.width!==1536||s.height!==1024)throw Error('Unexpected shadow atlas dimensions');const c=s.getContext('2d',{willReadFrequently:true});c.drawImage(shadowImage,0,0);const im=c.getImageData(0,0,s.width,s.height),d=im.data;
 for(let i=0;i<d.length;i+=4){const g=d[i+1]-Math.max(d[i],d[i+2]);if(g>25&&d[i+1]>85){d[i+3]=Math.round(255*(1-Math.min(1,(g-25)/65)));d[i+1]=Math.min(d[i+1],Math.max(d[i],d[i+2])+15)}}c.putImageData(im,0,0);
 const crops=[[0,0,384,512,187,435],[384,0,384,512,575,433],[768,0,384,512,980,433],[1152,0,384,512,1360,435],[0,512,420,512,187,916],[420,512,348,512,602,916],[768,512,384,512,980,916],[1152,512,384,512,1350,916]];
 for(const [x,y,w,h,ax,fy] of crops){const tile=isolateFrame(s,x,y,w,h),data=tile.getContext('2d').getImageData(0,0,w,h).data;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if((xx===0||yy===0||xx===w-1||yy===h-1)&&data[(yy*w+xx)*4+3]>40)throw Error('Shadow pose touches crop edge');shadowFrames.push({tile,anchor:ax-x,foot:fy-y})}
 shadow.ready=true;document.body.dataset.shadow='ready';
 }catch(e){document.body.dataset.shadow='error';log(e.message)}
};shadowImage.src='assets/shadow-poses.png';
function shadowFrame(state,t){if(state==='walk')return Math.floor(Math.max(0,t)*5)%2+1;if(['idle','hurt','death'].includes(state))return 0;const duration=CLIPS[state].duration;if(['mend','guard','potion'].includes(state))return t<duration*.15?0:t<duration*.82?7:6;const impact=CLIPS[state].impact;return t<impact*.45?0:t<impact?3:t<impact+.12?4:t<duration*.86?5:6}
function shadowSpirit(x,y,size,phase,opacity){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(phase)*.12);ctx.globalAlpha*=opacity;ctx.fillStyle='#110921';ctx.strokeStyle='#9149e6';ctx.lineWidth=1.5;ctx.shadowColor='#b955ff';ctx.shadowBlur=15;ctx.beginPath();ctx.moveTo(-size*.6,-size*.1);ctx.lineTo(-size*.65,-size);ctx.lineTo(-size*.22,-size*.66);ctx.quadraticCurveTo(0,-size*.8,size*.22,-size*.66);ctx.lineTo(size*.65,-size);ctx.lineTo(size*.6,-size*.1);ctx.quadraticCurveTo(size*.4,size*.5,0,size*.7);ctx.quadraticCurveTo(-size*.4,size*.5,-size*.6,-size*.1);ctx.fill();ctx.stroke();ctx.fillStyle='#edbcff';for(const sign of [-1,1]){ctx.beginPath();ctx.ellipse(sign*size*.25,-size*.23,size*.18,size*.055,sign*-.35,0,Math.PI*2);ctx.fill()}ctx.restore()}
const mortalPose=drawPose;drawPose=function(state,elapsed,x,y,face=1,opacity=1){if(!shadow.active||!shadow.ready)return mortalPose(state,elapsed,x,y,face,opacity);const t=shadow.elapsed,f=shadowFrames[shadowFrame(state,elapsed)],scale=.59,arrival=Math.min(1,t/.35);if(arrival<1)mortalPose(state,elapsed,x,y,face,opacity*(1-arrival));ctx.save();ctx.globalAlpha*=opacity*arrival;ctx.translate(x,y);
 ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha*=.22+.035*Math.sin(t*2);if(shadowAura.complete&&shadowAura.naturalWidth){ctx.translate(0,-104);ctx.rotate(Math.sin(t*.5)*.16);ctx.drawImage(shadowAura,-150,-155,300,300)}ctx.restore();
 const spirits=[];for(let j=0;j<3;j++){const a=t*1.5+j*Math.PI*2/3;spirits.push({a,x:Math.cos(a)*84,y:-90+Math.sin(a)*32,size:23+Math.sin(a)*5})}for(const q of spirits)if(Math.sin(q.a)<0)shadowSpirit(q.x,q.y,q.size,q.a,.45);
 ctx.save();ctx.scale(face,1);if(state==='walk'){const stride=elapsed*Math.PI*10;ctx.translate(Math.sin(stride)*1.8,-Math.abs(Math.sin(stride))*2);ctx.rotate(Math.sin(stride)*.012)}if(['attack','moon','whirl'].includes(state)){const impact=CLIPS[state].impact,progress=Math.max(0,Math.min(1,(elapsed-impact+.12)/.24)),lunge=Math.sin(progress*Math.PI);ctx.translate(lunge*12,0);ctx.rotate(-lunge*.035)}if(state==='idle')ctx.scale(1,1+Math.sin(t*1.8)*.004);if(state==='hurt')ctx.translate(-Math.sin(elapsed*10)*8,0);if(state==='death')ctx.rotate(-Math.min(1,elapsed/1.25)*1.45);ctx.shadowColor='#ae38ff';ctx.shadowBlur=9+Math.sin(t*4)*3;ctx.drawImage(f.tile,-f.anchor*scale,-f.foot*scale,f.tile.width*scale,f.tile.height*scale);ctx.restore();
 for(const q of spirits)if(Math.sin(q.a)>=0)shadowSpirit(q.x,q.y,q.size,q.a,.65);
 if(['attack','moon','whirl'].includes(state)){const u=(elapsed-CLIPS[state].impact)/.28;if(u>=0&&u<=1){ctx.save();ctx.scale(face,1);ctx.globalAlpha*=Math.sin(u*Math.PI);ctx.globalCompositeOperation='screen';ctx.shadowColor='#a53bff';ctx.shadowBlur=17;for(let j=0;j<3;j++){ctx.strokeStyle=j===1?'#f4d7ff':'#a954f5';ctx.lineWidth=4-j;ctx.beginPath();ctx.ellipse(30,-95,92+j*7,48+j*8,-.4,-1+u*1.5,1.2+u*1.5);ctx.stroke()}ctx.restore()}}
 ctx.globalCompositeOperation='screen';for(let j=0;j<16;j++){const a=t*1.1+j*2.4,r=40+j%4*13;ctx.save();ctx.globalAlpha*=Math.sin(((t*40+j*19)%210)/210*Math.PI);circle(Math.sin(a)*r,-(t*40+j*19)%210,1.5+j%3*.5,'#b967f7');ctx.restore()}
 ctx.restore()};
const shadowSceneDraw=draw;draw=function(){shadowSceneDraw();if(shadow.burst>0){const s=pos(p.x,p.y);ctx.save();ctx.globalAlpha=shadow.burst*.6;ctx.strokeStyle='#d9a2ff';ctx.shadowColor='#ab39ff';ctx.shadowBlur=25;ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(s.x,s.y-65,40+(1-shadow.burst)*150,20+(1-shadow.burst)*85,0,0,Math.PI*2);ctx.stroke();ctx.restore()}};
const shadowButton=document.createElement('button');shadowButton.id='shadowAbility';shadowButton.title='Shadow Ascension [5] · 40 spirit · 15 seconds · 60 second cooldown. Become the shadow katana form; +25% damage. Your equipped weapon statistics are retained.';shadowButton.innerHTML='<b style="background:url(assets/shadow-aura.png) center/contain no-repeat;color:transparent">✦</b><span>5 · Ascension</span><em></em>';$('.skills').append(shadowButton);shadowButton.onclick=ascendShadow;
function updateShadowButton(){shadowButton.disabled=!shadow.ready||shadow.cooldown>0||p.mp<40;shadowButton.setAttribute('aria-pressed',String(shadow.active));shadowButton.querySelector('em').textContent=shadow.active?Math.ceil(shadow.remaining)+'s form':shadow.cooldown>0?Math.ceil(shadow.cooldown)+'s':'';shadowButton.style.borderColor=shadow.active?'#d9a0ff':''}
addEventListener('keydown',e=>{if(e.code==='Digit5'&&!e.repeat&&!/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||'')){e.preventDefault();ascendShadow()}});
