const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');const nodes=new Map();function node(s){if(!nodes.has(s))nodes.set(s,{style:{},classList:{add(){},remove(){},toggle(){}},getContext(){return{}},addEventListener(){},showModal(){this.open=true},close(){this.open=false}});return nodes.get(s)}const store={};const sandbox={document:{querySelector:node,querySelectorAll:()=>[]},innerWidth:1280,innerHeight:800,addEventListener(){},requestAnimationFrame(){},localStorage:{getItem:k=>store[k],setItem:(k,v)=>store[k]=v},console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('game.js','utf8'),sandbox);function run(s){return vm.runInContext(s,sandbox)}run('running=true; talk()');assert.equal(node('#modal').open,true);node('#accept').onclick();assert.equal(run('p.quest'),1);run('for(let i=0;i<6;i++)hit(enemies[i],999)');assert.equal(run('p.kills'),6);assert.equal(run('p.level'),2);run('talk()');assert.equal(run('p.quest'),2);assert.equal(run('p.potions'),6);node('#modal').close();run('inventory()');node('#upgrade').onclick();assert.equal(run('p.weapon'),1);run('p.x=boss.x;p.y=boss.y;target=boss;p.mp=80;skill(0)');assert.ok(run('boss.hp<boss.max'));assert.equal(run('cooldown[0]'),4);let hp=run('boss.hp');run('skill(0)');assert.equal(run('boss.hp'),hp);run('hit(boss,9999);p.x=0;p.y=160;talk()');assert.equal(run('p.quest'),3);assert.equal(run('p.boss'),true);assert.equal(JSON.parse(store['catmurai-save']).quest,3);node('#modal').close();run('p.hp=10;p.potions=1;potion()');assert.equal(run('p.hp'),100);assert.equal(run('p.potions'),0);run('enemies[10].x=p.x;enemies[10].y=p.y;enemies[10].dead=0;update(.01)');assert.ok(run('p.hp>=100'));console.log('PASS: quest acceptance, six kills, leveling, rewards, upgrade, skill damage/cooldown, boss victory, chapter completion, save, potion, shrine safety');

// Renderer integration smoke test: load the real visual module and render all effects.
let imageDraws=0;const gradient={addColorStop(){}};const renderingContext=new Proxy({drawImage(){imageDraws++},createRadialGradient(){return gradient}},{get(t,k){return k in t?t[k]:()=>{}},set(t,k,v){t[k]=v;return true}});node('#world').getContext=()=>renderingContext;
const visualSandbox={...sandbox,Image:class{constructor(){this.complete=true;this.naturalWidth=1024}}};vm.createContext(visualSandbox);vm.runInContext(fs.readFileSync('game.js','utf8'),visualSandbox);vm.runInContext(fs.readFileSync('visuals.js','utf8'),visualSandbox);vm.runInContext("running=true;effects.push({type:'slash',x:0,y:0,life:.2},{type:'text',t:'42',x:0,y:0,c:'#fff',life:1});draw();p.x+=4;update(.016);draw()",visualSandbox);assert.ok(imageDraws>=2);console.log('PASS: upgraded renderer draws reference sprite, scene, enemies, and combat effects');

// Animation integration: delayed impacts, resource gates, action locks, preview and FPS independence.
vm.runInContext(fs.readFileSync('animation.js','utf8'),visualSandbox);
function motionRun(s){return vm.runInContext(s,visualSandbox)}
motionRun("running=true;motion.state='idle';p.x=500;p.y=400;p.hp=maxhp();p.mp=80;target=enemies[0];target.x=550;target.y=400;target.hp=65;target.dead=0;for(let i=1;i<enemies.length;i++){enemies[i].x=1500;enemies[i].y=-1300}skill(0)");
assert.equal(motionRun('motion.state'),'moon');assert.equal(motionRun('target.hp'),65);assert.equal(motionRun('p.mp'),68);motionRun('skill(1)');assert.equal(motionRun('p.mp'),68);
motionRun("keys={d:true};update(.1)");assert.equal(motionRun('p.x'),500);assert.equal(motionRun('target.hp'),65);motionRun('update(.41)');assert.ok(motionRun('enemies[0].hp<65'));
motionRun("motion.state='idle';motion.events=[];keys={};target=null;p.hp=20;cooldown[2]=0;p.mp=80;skill(2)");assert.equal(motionRun('p.hp'),20);motionRun('update(.3)');assert.ok(motionRun('p.hp<25'));motionRun('update(.3)');assert.ok(motionRun('p.hp>80'));
motionRun("motion.state='idle';cooldown[3]=0;skill(3)");assert.equal(motionRun('buff'),0);motionRun('update(.51)');assert.equal(motionRun('buff'),7);
assert.deepEqual(JSON.parse(motionRun('JSON.stringify(clipFrame("walk",.8))')),{row:0,col:0,progress:0});
for(const clip of ['idle','walk','attack','moon','whirl','mend','guard','hurt','death','potion']){motionRun(`enterPreview('${clip}');update(.1);draw()`);assert.equal(motionRun('motion.state'),clip)}
let goldBefore=motionRun('p.gold');motionRun('update(10)');assert.equal(motionRun('p.gold'),goldBefore);motionRun('exitPreview()');assert.equal(motionRun('motion.preview'),null);
for(const fps of [30,60,120]){motionRun("motion.state='idle';motion.elapsed=0;motion.events=[];p.x=0;p.y=160;target=null;destination=null;keys={d:true}");for(let i=0;i<fps;i++)motionRun(`update(${1/fps})`);assert.ok(Math.abs(motionRun('p.x')-220)<.001)}
console.log('PASS: delayed skill impacts, cast costs, duplicate action prevention, movement locks, heal/guard timing, every clip, preview isolation, and 30/60/120 FPS movement');



// Living world: delayed enemy strikes, dodging, safe zone, and death cancellation.
renderingContext.createLinearGradient=()=>gradient;
vm.runInContext(fs.readFileSync('world.js','utf8'),visualSandbox);
motionRun("running=true;motion.preview=null;motion.state='idle';p.x=500;p.y=400;p.hp=100;keys={};destination=null;target=null;enemies[0].x=550;enemies[0].y=400;enemies[0].dead=0;enemies[0].cd=2;queueEnemyStrike(enemies[0],10);advanceEnemyStrikes(.1)");assert.equal(motionRun('p.hp'),100);motionRun('advanceEnemyStrikes(.23)');assert.equal(motionRun('p.hp'),90);
motionRun('queueEnemyStrike(enemies[0],10);p.x=900;advanceEnemyStrikes(.4)');assert.equal(motionRun('p.hp'),90);
motionRun('p.x=0;p.y=160;enemies[0].x=0;enemies[0].y=160;queueEnemyStrike(enemies[0],10);advanceEnemyStrikes(.4)');assert.equal(motionRun('p.hp'),90);
motionRun('p.x=500;p.y=400;enemies[0].x=500;enemies[0].y=400;queueEnemyStrike(enemies[0],10);enemies[0].dead=20;advanceEnemyStrikes(.4)');assert.equal(motionRun('p.hp'),90);
motionRun('enemies[0].dead=0;p.hp=1;target=enemies[0];queueEnemyStrike(enemies[0],20);advanceEnemyStrikes(.4)');assert.equal(motionRun('p.x'),0);assert.equal(motionRun('target'),null);assert.equal(motionRun('enemyStrikes.length'),0);
assert.equal(motionRun('inStream(0,450)'),true);assert.equal(motionRun('inStream(0,0)'),false);motionRun('draw()');console.log('PASS: world renderer, stream regions, enemy strike delay, dodge, safe zone, canceled dead-enemy strike, respawn cleanup');

// Auto-farm: targeting boundaries, resources, pauses, manual stop and defeat.
for(const id of ['#autoFarm','#farmStatus'])node(id).setAttribute=function(k,v){this[k]=v};
vm.runInContext(fs.readFileSync('auto-farm.js','utf8'),visualSandbox);
motionRun("running=true;motion.preview=null;motion.state='idle';p.x=0;p.y=160;p.hp=maxhp();p.mp=80;target=null;destination=null;for(let i=0;i<enemies.length;i++){enemies[i].dead=0;enemies[i].x=1500;enemies[i].y=1200}enemies[0].x=300;enemies[0].y=160;enemies[1].x=500;enemies[1].y=160;boss.x=10;boss.y=160;toggleAutoFarm();farmThink()");assert.equal(motionRun('target.id'),0);assert.equal(motionRun('farm.enabled'),true);
motionRun('enemies[0].dead=20;farmThink()');assert.equal(motionRun('target.id'),1);motionRun('for(const e of enemies)if(e.kind!==2)e.dead=20;farmThink()');assert.equal(motionRun('target'),null);assert.match(motionRun('farm.status'),/Searching/);
motionRun('enemies[0].dead=0;farmThink()');assert.equal(motionRun('target.id'),0);
motionRun("p.hp=20;p.mp=80;cooldown[2]=0;motion.state='idle';farmThink()");assert.equal(motionRun('motion.state'),'mend');
motionRun("motion.state='idle';p.hp=10;p.mp=0;p.potions=1;farmThink()");assert.equal(motionRun('p.potions'),0);assert.equal(motionRun('motion.state'),'potion');
motionRun("motion.state='idle';p.hp=5;p.mp=0;p.potions=0;farmThink()");assert.equal(motionRun('farm.enabled'),false);assert.equal(motionRun('destination.y'),160);
motionRun("motion.state='idle';p.hp=maxhp();toggleAutoFarm();stopAutoFarm('Manual control')");assert.equal(motionRun('farm.enabled'),false);assert.equal(motionRun('target'),null);assert.equal(motionRun('destination'),null);
motionRun("toggleAutoFarm();target=null");node('#modal').open=true;motionRun('farmThink()');assert.equal(motionRun('target'),null);node('#modal').close();
motionRun("p.x=500;p.y=400;p.hp=1;enemies[0].x=500;enemies[0].y=400;enemies[0].dead=0;queueEnemyStrike(enemies[0],20);advanceEnemyStrikes(.4)");assert.equal(motionRun('farm.enabled'),false);assert.equal(motionRun('farm.status'),'Stopped after defeat');
console.log('PASS: auto-farm nearest target, boss exclusion, patrol, respawn reacquire, healing, potion, retreat, stop, dialog pause, death stop');

// Seek outside the former farm radius; patrol advances and interrupts on a respawn.
motionRun("motion.state='idle';motion.preview=null;p.hp=maxhp();p.mp=80;p.x=0;p.y=160;for(const e of enemies)e.dead=20;enemies[2].dead=0;enemies[2].x=1400;enemies[2].y=1000;toggleAutoFarm();farmThink()");assert.equal(motionRun('target.id'),2);assert.match(motionRun('farm.status'),/Seeking/);
motionRun('enemies[2].dead=20;farmThink()');assert.equal(motionRun('target'),null);assert.ok(motionRun('destination!==null'));let patrolBefore=motionRun('farm.patrolIndex');motionRun('p.x=destination.x;p.y=destination.y;farmThink()');assert.notEqual(motionRun('farm.patrolIndex'),patrolBefore);
motionRun('enemies[3].dead=0;enemies[3].x=p.x+100;enemies[3].y=p.y;farmThink()');assert.equal(motionRun('target.id'),3);assert.equal(motionRun('destination'),null);motionRun('stopAutoFarm()');assert.equal(motionRun('destination'),null);console.log('PASS: seeks distant enemies, patrols empty hunting spots, advances route, reacquires respawns, cancels patrol');

// Talents: point economy, requirements, persistence, migration, and real combat bonuses.
vm.runInContext(fs.readFileSync('talents.js','utf8'),visualSandbox);
motionRun('p.level=1;p.talents={};sanitizeTalents()');assert.equal(motionRun('talentPoints()'),0);assert.equal(motionRun("learnTalent('edge')"),false);
motionRun('p.level=10');assert.equal(motionRun('talentPoints()'),9);assert.equal(motionRun("learnTalent('focus')"),false);for(let i=0;i<3;i++)assert.equal(motionRun("learnTalent('edge')"),true);assert.equal(motionRun("learnTalent('edge')"),false);assert.equal(motionRun("learnTalent('focus')"),true);assert.equal(motionRun('talentPoints()'),5);assert.equal(JSON.parse(store['catmurai-save']).talents.focus,1);
motionRun("p.talents={vitality:3,armor:3,renewal:3};sanitizeTalents()");assert.equal(motionRun('maxhp()'),360);motionRun("p.x=500;p.y=400;p.hp=200;enemies[0].dead=0;enemies[0].x=500;enemies[0].y=400;queueEnemyStrike(enemies[0],100);advanceEnemyStrikes(.4)");assert.equal(motionRun('p.hp'),109);
motionRun("p.talents={edge:3,focus:3,execute:3};enemies[0].hp=300;enemies[0].max=1000;enemies[0].dead=0;instantHit(enemies[0],100)");assert.equal(motionRun('enemies[0].hp'),161);
motionRun("p.level=28;p.talents={spirit:3,mending:3,flow:3};sanitizeTalents();motion.state='idle';motion.events=[];cooldown[2]=0;p.mp=80;p.hp=100;skill(2)");assert.ok(Math.abs(motionRun('cooldown[2]')-10.92)<.0001);motionRun('enemies.forEach(e=>e.dead=20);update(.6)');assert.ok(motionRun('p.hp')>180);
motionRun('resetTalents()');assert.equal(motionRun('talentSpent()'),0);assert.equal(motionRun('talentPoints()'),27);
motionRun("p.level=3;p.talents={edge:999,focus:3,armor:3,spirit:-2,flow:1.5};sanitizeTalents()");assert.equal(motionRun('talentSpent()'),2);assert.equal(motionRun('p.talents.focus'),0);assert.equal(motionRun('p.talents.armor'),0);assert.equal(motionRun('p.talents.flow'),0);
console.log('PASS: talent points per level, prerequisites, rank cap, save persistence, health, armor, damage, healing, cooldowns, respec, invalid-save repair');
vm.runInContext(fs.readFileSync('enchantment.js','utf8'),visualSandbox);
for(const [level,tier] of [[0,0],[1,1],[3,1],[4,2],[6,2],[7,3],[9,3],[10,4],[14,4],[15,5],[999,5],[-1,0]])assert.equal(motionRun(`enchantStyle(${level}).tier`),tier);
assert.equal(motionRun('enchantStyle(Infinity).tier'),0);assert.equal(motionRun('enchantStyle(999).power'),1);
const beforeEnchant=motionRun('JSON.stringify(p)');
for(const level of [0,1,4,7,10,15,100])for(const sheet of ['walk',0,1,2,3])for(let frame=0;frame<(sheet==='walk'?8:6);frame++)motionRun(`drawWeaponEnchant('${sheet}',${frame},130,240,.8,${level},1.2)`);
assert.equal(motionRun('JSON.stringify(p)'),beforeEnchant);assert.equal(motionRun('BLADE_POSES[3][2]'),null);assert.equal(motionRun('BLADE_POSES[2][3]'),null);
console.log('PASS: enchant thresholds, invalid levels, capped intensity, all blade poses and tiers render, concealed blades suppressed, player unchanged');
vm.runInContext(fs.readFileSync('weapons.js','utf8').split('const vendorButton=')[0],visualSandbox);
motionRun("motion.state='idle';p.level=8;p.gold=1000;p.weapon=7;p.armory=null;p.equippedWeapon=null;restoreArmory()");assert.equal(motionRun('p.armory.moonsteel'),7);
assert.equal(motionRun("purchaseWeapon('ember')"),true);assert.equal(motionRun('p.gold'),760);assert.equal(motionRun("purchaseWeapon('ember')"),false);assert.equal(motionRun("purchaseWeapon('eclipse')"),false);
assert.equal(motionRun("equipWeapon('ember')"),true);assert.equal(motionRun('p.weapon'),0);assert.equal(motionRun('weaponDamage(100)'),112);assert.equal(motionRun('temperEquipped()'),true);assert.equal(motionRun('p.weapon'),1);motionRun("equipWeapon('moonsteel')");assert.equal(motionRun('p.weapon'),7);motionRun("equipWeapon('ember')");assert.equal(motionRun('p.weapon'),1);
assert.equal(JSON.parse(store['catmurai-save']).armory.ember,1);motionRun("p.level=1");assert.equal(motionRun("purchaseWeapon('jade')"),false);motionRun("p.level=8;p.gold=500;purchaseWeapon('jade');equipWeapon('jade')");assert.equal(motionRun('weaponDamage(100,true)'),126);assert.equal(motionRun('weaponDamage(100,false)'),105);motionRun("motion.state='attack';motion.elapsed=0");assert.equal(motionRun("equipWeapon('moonsteel')"),false);
console.log('PASS: legacy enchant migration, gold costs, duplicate/level/funds guards, equip, separate enchants, persistence, weapon damage and combat switching lock');
// Class combat without browser-only image loading.
vm.runInContext(fs.readFileSync('weapon-classes.js','utf8').split('const CLASS_CROPS=')[0],visualSandbox);
motionRun("p.armory.axe=0;p.armory.dual=0;p.armory.eclipse=0;motion.state='idle';equipWeapon('axe')");assert.equal(motionRun('CLIPS.attack.duration'),1.12);assert.equal(motionRun('CLIPS.attack.impact'),.56);
motionRun("equipWeapon('dual');motion.events=[];enemies[0].dead=0;hit(enemies[0],100)");assert.equal(motionRun('motion.events.length'),2);assert.equal(motionRun('motion.events[0].remaining'),.28);assert.equal(motionRun('motion.events[1].remaining'),.47);assert.equal(motionRun('motion.events[0].hitScale'),.5);
motionRun("p.talents={};enemies[0].hp=1000;enemies[0].max=1000;instantHit(enemies[0],100,.5);instantHit(enemies[0],100,.5)");assert.equal(motionRun('enemies[0].hp'),890);
motionRun("motion.state='idle';equipWeapon('eclipse')");assert.equal(motionRun('CLIPS.attack.duration'),1.3);motionRun("equipWeapon('moonsteel')");assert.equal(motionRun('CLIPS.attack.duration'),.72);
console.log('PASS: axe/greatsword cadence, two dual impacts, total dual damage, switching restores sword timing');
const classSource=fs.readFileSync('weapon-classes.js','utf8');vm.runInContext(classSource.slice(classSource.indexOf('function classSchedule'),classSource.indexOf('const CLASS_EDGES')),visualSandbox);
for(const type of ['axe','dual','greatsword']){const profile=motionRun(`CLASS_PROFILES.${type}`);assert.equal(motionRun(`classFrame('attack',${profile.impact-.001},'${type}')`),3);assert.equal(motionRun(`classFrame('attack',${profile.impact+.001},'${type}')`),4);assert.equal(motionRun(`classFrame('attack',${profile.duration*.93},'${type}')`),6);for(const state of ['idle','walk','attack','moon','whirl','mend','guard','hurt','death','potion'])for(let t=0;t<2;t+=.013){const frame=motionRun(`classFrame('${state}',${t},'${type}')`);assert.ok(Number.isInteger(frame)&&frame>=0&&frame<8)}}assert.equal(motionRun("classFrame('moon',.551,'dual')"),5);
console.log('PASS: weapon windup/contact/recovery boundaries, dual second contact, all class states return valid frames');
vm.runInContext(fs.readFileSync('bosses.js','utf8').split('const trialButton=')[0],visualSandbox);
motionRun("motion.state='idle';p.level=12;p.x=0;p.y=160;p.bossRewards={};p.bossTokens=0;p.talents={}");assert.equal(motionRun("beginTrial('moon')"),true);assert.equal(motionRun("beginTrial('fang')"),false);assert.equal(motionRun("warningContains({kind:'ring',x:0,y:0},0,0)"),false);assert.equal(motionRun("warningContains({kind:'ring',x:0,y:0},100,0)"),true);assert.equal(motionRun("warningContains({kind:'line',x:0,y:0,angle:0},0,80)"),false);
motionRun('trial.foe.hp=trial.foe.max*.4;updateTrial(.1)');assert.equal(motionRun('trial.phase'),2);motionRun('trialWarnings=[];trial.clock=10;p.x=trial.def.x;p.y=trial.def.y;trialWarnings.push({kind:"slam",x:p.x,y:p.y,remaining:.1});p.hp=maxhp();updateTrial(.2)');assert.ok(motionRun('p.hp<maxhp()'));
const originalQuestBoss=motionRun('p.boss');motionRun('claimBossReward(trial.foe)');assert.equal(motionRun('p.armory.moonrelic'),4);assert.equal(motionRun('p.bossTokens'),3);assert.equal(motionRun('p.boss'),originalQuestBoss);assert.equal(motionRun('trial'),null);motionRun("beginTrial('moon');claimBossReward(trial.foe)");assert.equal(motionRun('p.bossTokens'),4);motionRun('spendBossSeals()');assert.equal(motionRun('p.bossTokens'),1);assert.equal(motionRun("purchaseWeapon('stormrelic')"),false);motionRun("beginTrial('storm');p.x=0;p.y=160;updateTrial(.1)");assert.equal(motionRun('trial'),null);assert.equal(motionRun('trialWarnings.length'),0);
console.log('PASS: trial gating, ring/lane dodge geometry, enrage, damage, exclusive/ repeat rewards, seals, quest isolation, retreat cleanup');
for(const type of ['axe','dual','greatsword']){for(let t=0;t<2;t+=.03)assert.ok([1,2].includes(motionRun(`classFrame('walk',${t},'${type}')`)));assert.equal(motionRun(`classFrame('guard',0,'${type}')`),0);assert.equal(motionRun(`classFrame('guard',.5,'${type}')`),7);assert.equal(motionRun(`classFrame('guard',1,'${type}')`),6)}
console.log('PASS: walking excludes standing pose; casting enters and recovers; shared timeline retains contact timing');
vm.runInContext(fs.readFileSync('shadow.js','utf8').split('const shadowFrames=')[0],visualSandbox);
motionRun("running=true;motion.preview=null;motion.state='idle';motion.elapsed=0;shadow.ready=true;p.mp=80;p.hp=maxhp();p.equippedWeapon='axe';p.armory.axe=3;p.weapon=3");
const beforeArmory=motionRun('JSON.stringify(p.armory)'),beforeDamage=motionRun('weaponDamage(100)');
assert.equal(motionRun('ascendShadow()'),true);assert.equal(motionRun('p.mp'),40);assert.equal(motionRun('weaponClass()'),'sword');assert.equal(motionRun('weaponDamage(100)'),Math.round(beforeDamage*1.25));assert.equal(motionRun('ascendShadow()'),false);assert.equal(motionRun('p.mp'),40);
motionRun("motion.state='idle';tickShadow(15)");assert.equal(motionRun('shadow.active'),false);assert.equal(motionRun('weaponClass()'),'axe');assert.equal(motionRun('p.weapon'),3);assert.equal(motionRun('JSON.stringify(p.armory)'),beforeArmory);assert.equal(motionRun('shadow.cooldown'),45);assert.equal(motionRun('ascendShadow()'),false);
motionRun('tickShadow(45);p.mp=39');assert.equal(motionRun('ascendShadow()'),false);motionRun("p.mp=80;ascendShadow();tickShadow(.1,true)");assert.equal(motionRun('shadow.active'),false);assert.equal(motionRun('weaponDamage(100)'),beforeDamage);
console.log('PASS: Shadow Ascension cost, duplicate cast prevention, bonus, duration, cooldown, equipment restoration, insufficient spirit, defeat cleanup');
vm.runInContext(fs.readFileSync('shadow.js','utf8').split('function shadowFrame')[1].split('function shadowSpirit')[0].replace(/^/, 'function shadowFrame'),visualSandbox);
for(const state of ['idle','walk','attack','moon','whirl','mend','guard','hurt','death','potion'])for(let t=0;t<2;t+=.017)assert.ok(motionRun(`shadowFrame('${state}',${t})`)>=0&&motionRun(`shadowFrame('${state}',${t})`)<8);
motionRun("shadow.active=true;shadow.remaining=.01;motion.state='attack';motion.elapsed=0;tickShadow(.02)");assert.equal(motionRun('shadow.active'),true);assert.equal(motionRun('weaponDamage(100)'),beforeDamage);motionRun("motion.state='idle';tickShadow(.01)");assert.equal(motionRun('shadow.active'),false);
console.log('PASS: all shadow animation states use valid poses; expiry finishes attacks without extending damage bonus');
vm.runInContext(fs.readFileSync('weapon-classes.js','utf8').split('function weaponWeight')[1].split('function weaponContactTrail')[0].replace(/^/,'function weaponWeight'),visualSandbox);
for(const type of ['axe','dual','greatsword'])for(const state of ['walk','attack','moon','whirl']){let previous=null;for(let t=0;t<2;t+=.001){const pose=motionRun(`weaponWeight('${state}',${t},'${type}')`);assert.ok(Number.isFinite(pose.x)&&Number.isFinite(pose.angle));if(previous)assert.ok(Math.abs(pose.x-previous.x)<.4,'Continuous weight shift');previous=pose}}
console.log('PASS: weapon weight curves remain finite and continuous through contact and recovery');
vm.runInContext(fs.readFileSync('weapon-travel.js','utf8').match(/function travelFrame\(t\)\{[^}]+\}/)[0],visualSandbox);
for(let i=0;i<8;i++)assert.equal(motionRun(`travelFrame(${i*.1+.000001})`),[0,1,3,2,4,5,7,6][i]);assert.equal(motionRun('travelFrame(.8)'),0);assert.equal(motionRun('travelFrame(0)'),0);
console.log('PASS: dedicated travel cycle visits all eight frames and loops at a fixed travel distance');
vm.runInContext(fs.readFileSync('locomotion.js','utf8'),visualSandbox);
const smoothResults=[];for(const fps of [30,60,120]){let v=0;for(let i=0;i<fps;i++)v=motionRun(`locomotionEase(${v},1,${1/fps})`);smoothResults.push(v)}assert.ok(Math.max(...smoothResults)-Math.min(...smoothResults)<1e-10);
motionRun("var gaitTest={state:'idle',elapsed:1,blend:1,lean:0,previous:null};advanceLocomotion(gaitTest,'walk',.1,2,.016)");assert.equal(motionRun('gaitTest.previous.state'),'idle');motionRun("advanceLocomotion(gaitTest,'attack',0,0,.016)");assert.equal(motionRun('gaitTest.previous'),null);assert.equal(motionRun('gaitTest.blend'),1);motionRun("advanceLocomotion(gaitTest,'idle',0,0,.2)");assert.equal(motionRun('gaitTest.previous'),null);
console.log('PASS: frame-rate independent locomotion settling; idle/walk blends; skill transitions bypass blending');
for(let x=-1800;x<=1800;x+=37){assert.equal(motionRun(`dryGround(${x},streamY(${x}))`),false);assert.equal(motionRun(`dryGround(${x},streamY(${x})+160,45)`),true);assert.equal(motionRun(`inStream(${x},streamY(${x})+69)`),true)}
console.log('PASS: river channel and scenery clearance remain consistent along the full river');
