/* Dedicated travel atlas: distance-driven eight-pose gait, no combat poses. */
const travelFrames=[],travelImage=new Image();
travelImage.onload=()=>{try{const s=document.createElement('canvas');s.width=travelImage.naturalWidth;s.height=travelImage.naturalHeight;const c=s.getContext('2d',{willReadFrequently:true});c.drawImage(travelImage,0,0);const im=c.getImageData(0,0,s.width,s.height),d=im.data;for(let i=0;i<d.length;i+=4){const g=d[i+1]-Math.max(d[i],d[i+2]);if(g>25&&d[i+1]>85){d[i+3]=Math.round(255*(1-Math.min(1,(g-25)/65)));d[i+1]=Math.min(d[i+1],Math.max(d[i],d[i+2])+15)}}c.putImageData(im,0,0);
const feet=[252,500,740,982,1228,1470];for(let row=0;row<6;row++){for(let col=0;col<4;col++){const x=Math.max(0,col*256-12),y=row*256,w=Math.min(1024-x,280),tile=isolateFrame(s,x,y,w,256,true);travelFrames.push({tile,anchor:col*256+128-x,foot:feet[row]-y,sx:x,sy:y})}}document.body.dataset.travel='ready'}catch(e){log('Travel animation: '+e.message)}};travelImage.src='assets/weapon-walk.png';
const travelBasePose=drawPose;
function travelFrame(t){return [0,1,3,2,4,5,7,6][Math.floor(Math.max(0,t)/.8*8)%8]}
drawPose=function(state,t,x,y,face=1,opacity=1){const r=CLASS_PROFILES[weaponClass()].row;if(state!=='walk'||r===undefined||travelFrames.length!==24)return travelBasePose(state,t,x,y,face,opacity);const frame=travelFrame(t),f=travelFrames[r*8+frame],scale=1.00;ctx.save();ctx.globalAlpha*=opacity;ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(f.tile,-f.anchor*scale,-f.foot*scale,f.tile.width*scale,f.tile.height*scale);const row=r*2+Math.floor(frame/4),col=frame%4,offsetX=col*256-f.sx,offsetY=row*256-f.sy;
const edges=r===0?[[207,154,233,204]]:r===1?[[93,157,25,189],[172,157,239,187]]:[[142,155,250,210]];
for(const edge of edges){BLADE_POSES.travel=[edge.map((v,i)=>v+(i%2?offsetY:offsetX))];armoryGlow('travel',0,f.anchor,f.foot,scale)}ctx.restore()};
const travelStep=$('#animationStep').onclick;$('#animationStep').onclick=()=>{if(motion.state!=='walk'||CLASS_PROFILES[weaponClass()].row===undefined)return travelStep();motion.paused=true;$('#animationPause').textContent='Resume';motion.elapsed=((Math.floor(motion.elapsed/.1+1e-6)+1)%8)*.1+.000001};
