/* Persistent armory: each blade owns its enchantment level. */
const WEAPONS=[
 {id:'fangrelic',type:'axe',rewardOnly:true,name:'Fang of the Oni',price:0,level:4,damage:48,skill:.15,color:'#ff916e',desc:'Exclusive Awakened Fang relic · heavy axe.'},
 {id:'moonrelic',type:'dual',rewardOnly:true,name:'Moonlit Twins',price:0,level:7,damage:24,skill:.25,color:'#c49aff',desc:'Exclusive Broken Moon relic · dual swords.'},
 {id:'stormrelic',type:'greatsword',rewardOnly:true,name:'Thunder Sovereign',price:0,level:10,damage:52,skill:.2,color:'#82e9ef',desc:'Exclusive Stormforged relic · two-handed sword.'},
 {id:'axe',type:'axe',name:'Crimson Battle Axe',price:620,level:5,damage:38,skill:.1,color:'#ffba83',desc:'Battle axe · heavy overhead chop · 1.30s basic cadence.'},
 {id:'dual',type:'dual',name:'Twin Crescent Swords',price:720,level:6,damage:10,skill:.15,color:'#8bdfeb',desc:'Dual swords · two alternating half-damage hits · 0.88s cadence.'},
 {id:'moonsteel',name:'Moonsteel Katana',price:0,level:1,damage:0,skill:0,color:'#ccd9ed',desc:'Balanced clan steel. Your original blade.'},
 {id:'ember',name:'Emberfang Saber',price:240,level:3,damage:12,skill:0,color:'#ffb66e',desc:'Flame-forged steel. +12 damage on every weapon hit.'},
 {id:'jade',name:'Jade Spirit Blade',price:480,level:5,damage:5,skill:.2,color:'#82edc5',desc:'+5 weapon damage and +20% Moon Cut / Whirlwind damage.'},
 {id:'eclipse',type:'greatsword',name:'Eclipse Greatblade',price:900,level:8,damage:26,skill:.1,color:'#ce9ff5',desc:'Two-handed greatsword · broad heavy sweep · +26 damage, +10% skill damage · 1.50s cadence.'}
];
function equippedWeapon(){return WEAPONS.find(w=>w.id===p.equippedWeapon)||WEAPONS.find(w=>w.id==='moonsteel')}
function restoreArmory(){const owned=p.armory&&typeof p.armory==='object'?p.armory:{};const clean={};for(const w of WEAPONS)if(Number.isInteger(owned[w.id])&&owned[w.id]>=0)clean[w.id]=owned[w.id];if(clean.moonsteel===undefined)clean.moonsteel=Number.isInteger(p.weapon)&&p.weapon>=0?p.weapon:0;p.armory=clean;if(clean[p.equippedWeapon]===undefined)p.equippedWeapon='moonsteel';p.weapon=clean[p.equippedWeapon]}
restoreArmory();
function purchaseWeapon(id){const w=WEAPONS.find(w=>w.id===id);if(!w||w.rewardOnly||p.armory[id]!==undefined||p.level<w.level||p.gold<w.price)return false;p.gold-=w.price;p.armory[id]=0;save();return true}
function equipWeapon(id){if(p.armory[id]===undefined||!WEAPONS.some(w=>w.id===id)||busy())return false;p.armory[p.equippedWeapon]=p.weapon;p.equippedWeapon=id;p.weapon=p.armory[id];save();return true}
function temperEquipped(){const cost=(p.weapon+1)*60;if(p.gold<cost||busy())return false;p.gold-=cost;p.weapon++;p.armory[p.equippedWeapon]=p.weapon;save();return true}
function weaponDamage(d,skillHit=false){const w=equippedWeapon();return Math.round((d+w.damage)*(skillHit?1+w.skill:1))}
const SMITH={x:155,y:60};
function openWeapons(shop=false){if(shop&&Math.hypot(p.x-SMITH.x,p.y-SMITH.y)>230){log('Visit Kaji at the shrine forge (155, 60).');return}if(busy()){log('Finish your current action before changing weapons.');return}if(typeof stopAutoFarm==='function')stopAutoFarm();target=null;destination=null;keys={};const w=equippedWeapon(),e=enchantStyle(p.weapon);modal(`<small>${shop?'CRIMSON FORGE · WEAPON VENDOR':'CHARACTER · ARMORY'}</small><h2>${shop?'Kaji the Bladesmith':'Your weapons'}</h2><p>${p.gold} gold · Level ${p.level} · Equipped: ${w.name} +${p.weapon}</p><div class="weapon-grid">${WEAPONS.map(b=>{const owned=p.armory[b.id]!==undefined,active=b.id===p.equippedWeapon;return `<article style="border-top:3px solid ${b.color}"><h3 style="color:${b.color}">⚔ ${b.name}${owned?' +'+p.armory[b.id]:''}</h3><p>${b.desc}</p><small>Requires level ${b.level}</small><p>${active?'Equipped':owned?'Owned':b.rewardOnly?'Boss reward':b.price+' gold'}</p><button data-weapon="${b.id}" ${active||(!owned&&(b.rewardOnly||!shop||p.level<b.level||p.gold<b.price))?'disabled':''}>${active?'Equipped':owned?'Equip':b.rewardOnly?'Earn in Boss Trials':shop?'Purchase':'Visit Kaji to buy'}</button></article>`}).join('')}</div><p style="color:${e.color}">✦ ${e.name} · Basic hit ${15+p.level*5+p.weapon*8+w.damage} before talents</p><button id="temperWeapon" ${p.gold<(p.weapon+1)*60?'disabled':''}>Temper ${w.name} · ${(p.weapon+1)*60} gold</button><p class="muted">Each weapon keeps its own enchantment. Purchases enter your armory; equip them here. V opens Kaji’s shop near the shrine.</p>`);document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>{const id=b.dataset.weapon;if(p.armory[id]!==undefined)equipWeapon(id);else if(shop)purchaseWeapon(id);openWeapons(shop)});$('#temperWeapon').onclick=()=>{temperEquipped();openWeapons(shop)}}
inventory=()=>openWeapons(false);$('#inventory').onclick=inventory;
const vendorButton=document.createElement('button');vendorButton.textContent='Kaji · Weapons [V]';vendorButton.onclick=()=>openWeapons(true);$('#talk').after(vendorButton);
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='v'&&running&&!$('#modal').open&&!motion.preview){e.preventDefault();openWeapons(true)}});
const armoryElder=drawElder;drawElder=function(){armoryElder();const s=pos(SMITH.x,SMITH.y);ellipse(s.x,s.y,30,10,'#06121c80');ctx.save();ctx.filter='sepia(.4)';npcSprite(0,time%3>2.7?3:0,s.x,s.y,115,-1);ctx.restore();ctx.fillStyle='#3d4658';ctx.fillRect(s.x-30,s.y-28,60,15);line(s.x-35,s.y-30,s.x+36,s.y-30,'#acb5c5',6);text('⚒ Kaji · Weapons [V]',s.x,s.y-132,'#efc481',11)};
const armoryUpdate=update;update=function(dt){armoryUpdate(dt);if(running)$('#stats').textContent=`✦ ${p.gold} GOLD · ${p.xp} / ${p.level*100} XP · ${equippedWeapon().name.toUpperCase()} +${p.weapon}`};
// Blade finish follows the same registered segment as its enchantment aura.
const armoryGlow=drawWeaponEnchant;drawWeaponEnchant=function(sheet,frame,anchor,foot,scale,level=p.weapon,clock=time){const b=BLADE_POSES[sheet]?.[frame],w=equippedWeapon();if(b&&w.id!=='moonsteel'){ctx.save();ctx.strokeStyle=w.color;ctx.lineWidth=w.id==='eclipse'?4:2.5;ctx.lineCap='round';ctx.globalAlpha*=.85;ctx.beginPath();ctx.moveTo((b[0]-anchor)*scale,(b[1]-foot)*scale);ctx.lineTo((b[2]-anchor)*scale,(b[3]-foot)*scale);ctx.stroke();ctx.restore()}armoryGlow(sheet,frame,anchor,foot,scale,level,clock)};
