/* Living Vale: illustrated scenery, animated terrain and world actors. */
const worldArt={props:[],npcs:[],ready:0,failures:[]};
function loadWorldAtlas(url,cols,rows,destination){const img=new Image();img.onload=()=>{try{const s=document.createElement('canvas');s.width=img.naturalWidth;s.height=img.naturalHeight;const c=s.getContext('2d',{willReadFrequently:true});c.drawImage(img,0,0);const im=c.getImageData(0,0,s.width,s.height),d=im.data;for(let i=0;i<d.length;i+=4){let excess=d[i+1]-Math.max(d[i],d[i+2]);if(excess>25&&d[i+1]>85){d[i+3]=Math.round(255*(1-Math.min(1,(excess-25)/65)));d[i+1]=Math.min(d[i+1],Math.max(d[i],d[i+2])+12)}}c.putImageData(im,0,0);const cw=s.width/cols,ch=s.height/rows;for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const bands=destination===worldArt.npcs?[[0,250],[252,227],[480,246],[727,297]]:null;let tile=isolateFrame(s,Math.floor(col*cw)+2,bands?bands[row][0]:Math.floor(row*ch)+2,(bands&&row===2&&col===4?286:Math.floor(cw)-4),bands?bands[row][1]:Math.floor(ch)-4);destination.push({image:tile,...worldBounds(tile)})}worldArt.ready++;document.body.dataset.worldArt=String(worldArt.ready)}catch(e){worldArt.failures.push(url);log('World art failed to decode: '+url)}};img.onerror=()=>{worldArt.failures.push(url);log('Missing world art: '+url)};img.src=url}
function worldBounds(tile){const d=tile.getContext('2d').getImageData(0,0,tile.width,tile.height).data;let x0=tile.width,y0=tile.height,x1=0,y1=0;for(let y=0;y<tile.height;y++)for(let x=0;x<tile.width;x++)if(d[(y*tile.width+x)*4+3]>70){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y)}return{x0,y0,x1,y1,width:x1-x0+1,height:y1-y0+1}}
function prop(index,x,y,height,sway=0,opacity=1){const a=worldArt.props[index];if(!a)return false;let scale=height/a.height,w=a.image.width*scale,h=a.image.height*scale;ctx.save();ctx.globalAlpha=opacity;ctx.translate(x-(a.x0+a.width/2)*scale,y-a.y1*scale);if(sway){const strips=12;for(let i=0;i<strips;i++){let sy=i*a.image.height/strips,sh=a.image.height/strips;let shift=sway*Math.pow(1-i/strips,1.6);ctx.drawImage(a.image,0,sy,a.image.width,sh,shift,sy*scale,w,sh*scale+.35)}}else ctx.drawImage(a.image,0,0,w,h);ctx.restore();return true}
const groundTufts=Array.from({length:950},(_,i)=>({x:noise(i+1700)*3500-1750,y:noise(i+2500)*2700-1350,size:3+noise(i+6300)*8,seed:i}));
function streamY(x){return 450+Math.sin(x/350)*90}
function inStream(x,y){return Math.abs(y-streamY(x))<62}
function waterPath(offset){ctx.beginPath();for(let x=-1900;x<=1900;x+=45){let s=pos(x,streamY(x)+offset);if(x===-1900)ctx.moveTo(s.x,s.y);else ctx.lineTo(s.x,s.y)}}
function worldGround(){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#172d36');g.addColorStop(.5,'#29463e');g.addColorStop(1,'#142e3a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<300;i++){let x=noise(i+9120)*3500-1750,y=noise(i+9920)*2700-1350,s=pos(x,y);if(s.x<-100||s.x>W+100||s.y<-70||s.y>H+70||inStream(x,y))continue;ellipse(s.x,s.y,25+noise(i+60)*65,10+noise(i+80)*22,i%3?'#45664518':'#0b29291c')}for(const t of groundTufts){const s=pos(t.x,t.y);if(s.x<-25||s.x>W+25||s.y<-25||s.y>H+25)continue;let road=Math.abs(t.y+t.x*.332)<90,plaza=Math.hypot(t.x,t.y)<245;if(road||plaza||inStream(t.x,t.y))continue;const wind=Math.sin(time*1.5+t.x*.02+t.y*.007)*2;for(let j=0;j<3;j++)line(s.x+j*3,s.y,s.x+j*3+wind+(j-1)*2,s.y-t.size,'#56796770',1);if(t.seed%7===0){circle(s.x,s.y-t.size,2.3,'#c496b690');circle(s.x+5,s.y-t.size+3,1.8,'#d5b3c1a0')}if(t.seed%5===0)ellipse(s.x,s.y+2,13,3,'#08242125')}
ctx.lineCap='round';for(const [width,color]of [[103,'#102b30'],[93,'#567970'],[82,'#214756'],[66,'#2d6572']]){waterPath(0);ctx.lineWidth=width;ctx.strokeStyle=color;ctx.stroke()}for(let i=0;i<65;i++){const x=-1800+i*57+(time*15)%57,y=streamY(x)+Math.sin(i*2.7)*40,s=pos(x,y);ctx.strokeStyle='#9bc9c344';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(s.x,s.y,12+Math.sin(i)*7,2,0,0,Math.PI);ctx.stroke()}for(let i=0;i<11;i++){const x=-700+i*130+Math.sin(time*.3+i)*24,y=streamY(x)+Math.cos(time*.4+i)*18,s=pos(x,y);ctx.save();ctx.globalAlpha=.42;ctx.translate(s.x,s.y);ctx.rotate(Math.sin(time+i)*.2);ellipse(0,0,8,3,i%2?'#e8bd88':'#a9c8c0');polygon([[-7,0],[-13,-4],[-13,4]],'#b4a287');ctx.restore()}for(let i=0;i<110;i++){let x=-1800+i*34,y=streamY(x)+(i%2?1:-1)*(65+noise(i+771)*11),s=pos(x,y);ellipse(s.x,s.y,3+noise(i+30)*6,2+noise(i+57)*3,i%3?'#718983':'#445f60')}for(let j=0;j<6;j++){let s=pos(-160+(j%2)*8,streamY(-160)-64+j*25);ellipse(s.x,s.y+2,15,6,'#17323b');ellipse(s.x,s.y,13,5,'#89918a');line(s.x-7,s.y-2,s.x+5,s.y-3,'#b0b3a0',1)}ctx.lineCap='butt';
}
const oldWorldTree=tree;
tree=function(t){let s=pos(t.x,t.y),h=t.size*3.9;if(s.x<-h||s.x>W+h||s.y<-30||s.y>H+h)return;let near=Math.abs(t.x-p.x)<90&&t.y>p.y&&t.y-p.y<230;ellipse(s.x,s.y,h*.27,h*.065,'#051e2945');if(!prop(t.pink?0:3,s.x,s.y,h,Math.sin(time*1.3+t.x*.03)*3,near?.35:1))oldWorldTree(t)};
const oldWorldShrine=shrine;
shrine=function(){let s=pos(0,-105);if(!prop(1,s.x,s.y,290)){oldWorldShrine();return}glow(s.x-69,s.y-97,65,'#efab5030');glow(s.x+65,s.y-95,65,'#efab5030');for(let side of [-1,1]){const xx=s.x+side*135,yy=s.y-155;line(xx,yy,xx+Math.sin(time*2)*2,yy+21,'#b19a6a',1);circle(xx+Math.sin(time*2)*2,yy+24,3,'#d6b87c')}for(let i=0;i<8;i++){let u=(time*.2+i*.125)%1;ellipse(s.x+Math.sin(u*7+i)*10,s.y-80-u*60,4+u*8,2+u*5,'#e6d6c512')}};
const oldWorldGate=gate;
gate=function(x,y){let s=pos(x,y);if(!prop(2,s.x,s.y,220)){oldWorldGate(x,y);return}for(let j=-1;j<=1;j++){let xx=s.x+j*28,yy=s.y-133;ctx.strokeStyle='#e8ddbd';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(xx,yy);for(let k=1;k<=4;k++)ctx.lineTo(xx+Math.sin(time*2+k*.7+j)*3+(k%2)*5,yy+k*7);ctx.stroke()}};
const oldWorldLantern=lantern;
lantern=function(x,y){let s=pos(x,y),flicker=.92+Math.sin(time*9+x)*.05+Math.sin(time*13+y)*.03;glow(s.x,s.y-48,94*flicker,'#ffb76c32');if(!prop(5,s.x,s.y,83))oldWorldLantern(x,y)};
const oldWorldRock=rock;
rock=function(x,y,r){if(x<-70||x>W+70||y<-40||y>H+90)return;if(!prop(4,x,y,r*2.6))oldWorldRock(x,y,r)};
let npcStates=new Map(),elderTalk=0;
function npcFrame(a){let state=npcStates.get(a.id);if(!state){state={x:a.x,y:a.y,phase:0,moving:false,face:1,attack:0};npcStates.set(a.id,state)}return state}
const animatedWorldUpdate=update;
update=function(dt){const paused=!running||$('#modal').open||document.hidden||motion.preview;const before=enemies.map(e=>({e,x:e.x,y:e.y,cd:e.cd}));animatedWorldUpdate(dt);if(paused)return;elderTalk=Math.max(0,elderTalk-dt);for(const b of before){let n=npcFrame(b.e),d=Math.hypot(b.e.x-b.x,b.e.y-b.y);n.moving=d>.05;n.phase+=d/90;if(Math.abs(b.e.x-b.x)>.05)n.face=b.e.x>b.x?1:-1;if(b.e.cd>b.cd+.5)n.attack=.65;n.attack=Math.max(0,n.attack-dt);n.x=b.e.x;n.y=b.e.y}};
function npcSprite(row,col,x,y,height,face=1){const a=worldArt.npcs[row*6+col];if(!a)return false;const rowAssets=worldArt.npcs.slice(row*6,row*6+6);const stableHeight=Math.max(...rowAssets.map(f=>f.height));let scale=height/stableHeight,foot=Math.max(...rowAssets.map(f=>f.y1));ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(a.image,-(a.x0+a.width/2)*scale,-foot*scale,a.image.width*scale,a.image.height*scale);ctx.restore();return true}
function drawElder(){const s=pos(0,0);ellipse(s.x,s.y,26,9,'#06121c80');let frame=elderTalk>0?[2,3,4,5][Math.min(3,Math.floor((2-elderTalk)*2))]:(time%4>3.82?1:0);if(!npcSprite(0,frame,s.x,s.y,133)){circle(s.x,s.y-50,18,'#d9c9ab');polygon([[s.x-18,s.y-40],[s.x-25,s.y],[s.x+25,s.y]],'#bba67f')}text('◆',s.x,s.y-168,'#efd299',19);text('Elder Mochi',s.x,s.y-146,'#f0ddbd',11)}
const worldActor=actor;
actor=function(a,kind){if(kind===0){worldActor(a,kind);return}let s=pos(a.x,a.y);if(s.x<-160||s.x>W+160||s.y<-40||s.y>H+280)return;const n=npcFrame(a);let col=n.attack>0?3+Math.min(2,Math.floor((.65-n.attack)/.22)):n.moving?[1,0,2,0][Math.floor(n.phase*5)%4]:0;let h=kind===3?215:kind===1?100:155;ellipse(s.x,s.y,kind===3?50:30,kind===3?17:10,'#03121b85');if(a===target){ctx.strokeStyle='#faad80';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(s.x,s.y,kind===3?59:37,kind===3?22:14,0,0,7);ctx.stroke()}ctx.save();if(a.flash)ctx.filter='brightness(1.7)';if(!npcSprite(kind,col,s.x,s.y,h,n.face)){ctx.restore();worldActor(a,kind);return}ctx.restore();text(a.name,s.x,s.y-h-17,kind===3?'#eaa59b':'#d4c9c4',kind===3?12:10);ctx.fillStyle='#0a1724';ctx.fillRect(s.x-28,s.y-h-9,56,4);ctx.fillStyle=kind===3?'#d7727f':'#b27991';ctx.fillRect(s.x-28,s.y-h-9,56*a.hp/a.max,4);if(n.attack>.12&&n.attack<.35){ctx.save();ctx.strokeStyle=kind===1?'#cce8ea':'#eb9c9b';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(s.x+n.face*26,s.y-50,45,23,-.3,0,2.5);ctx.stroke();ctx.restore()}};
function worldExtraItems(items){for(let i=0;i<16;i++){let x=-700+i*115,y=streamY(x)+90;items.push({y,draw:()=>{let s=pos(x,y);for(let j=0;j<4;j++)line(s.x+j*4,s.y,s.x+j*4+Math.sin(time*1.5+j)*4,s.y-20-j%2*10,'#729482',2)}})}items.push({y:315,draw:()=>{let s=pos(-440,315);prop(4,s.x,s.y,110)}})}
function worldAtmosphere(){for(let i=0;i<14;i++){let x=-550+i*100,y=streamY(x)+Math.sin(time*.5+i)*60,s=pos(x,y);let flap=Math.abs(Math.sin(time*10+i));ellipse(s.x-3,s.y,3*flap,2,'#d2b4d3aa');ellipse(s.x+3,s.y,3*flap,2,'#e7c4ddaa')}if(inStream(p.x,p.y)&&p.moving){let s=pos(p.x,p.y);ctx.strokeStyle='#b5e0dd88';ctx.lineWidth=1;for(let j=0;j<3;j++){let r=((time*24+j*12)%36);ctx.globalAlpha=1-r/36;ctx.beginPath();ctx.ellipse(s.x,s.y,r,r*.35,0,0,7);ctx.stroke()}ctx.globalAlpha=1}}
const drawWorldBase=draw;draw=function(){drawWorldBase();if(running)worldAtmosphere()};
const elderOriginalTalk=talk;talk=function(){elderTalk=2;elderOriginalTalk()};$('#talk').onclick=()=>talk();
loadWorldAtlas('assets/vale-props.png',3,2,worldArt.props);loadWorldAtlas('assets/vale-npcs.png',6,4,worldArt.npcs);
const enemyStrikes=[];
function queueEnemyStrike(e,damage){enemyStrikes.push({e,damage,remaining:.32});npcFrame(e).attack=.65}
function advanceEnemyStrikes(dt){for(const strike of enemyStrikes){strike.remaining-=dt;if(strike.remaining>0||strike.e.dead||Math.hypot(p.x,p.y)<240||Math.hypot(strike.e.x-p.x,strike.e.y-p.y)>105)continue;const applied=strike.damage*(typeof talentBonus==='function'?1-talentBonus('armor'):1);p.hp-=applied;float(Math.round(applied),p.x,p.y-55,'#ff9387');if(p.hp<=0){motion.ghosts.push({x:p.x,y:p.y,face:motion.facing,elapsed:0,duration:1.25,death:true});p.hp=maxhp();p.mp=80;p.x=0;p.y=160;p.gold=Math.max(0,p.gold-15);target=null;destination=null;keys={};motion.events=[];startMotion('idle');if(typeof stopAutoFarm==='function'&&farm.enabled)stopAutoFarm('Stopped after defeat');log('The shrine restores you · 15 gold lost');save();enemyStrikes.length=0;break}else if(!busy())startMotion('hurt')}for(let i=enemyStrikes.length-1;i>=0;i--)if(enemyStrikes[i].remaining<=0)enemyStrikes.splice(i,1)}
const worldUpdateWithStrikes=update;update=function(dt){const active=running&&!$('#modal').open&&!document.hidden&&!motion.preview;worldUpdateWithStrikes(dt);if(active)advanceEnemyStrikes(dt)};


function drawWorldCorpse(e){let s=pos(e.x,e.y),row=e.kind===2?3:e.kind===1?2:1;return npcSprite(row,5,s.x,s.y,row===3?215:row===1?100:155,npcFrame(e).face)}

